version: '3.8'
services:
  greensave_db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/greensave/data
volumes:
  db:
    driver: local
