import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import Providers from "./providers";
import TopBarNav from "@/components/TopNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-green-500 to-green-700 relative overflow-hidden`}
      >
        <Providers>
          <TopBarNav></TopBarNav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
